name: PropCount

services:
  web:
    image: ghcr.io/koj10/arenda:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    profiles: ["certs"]

volumes:
  certbot_www:
  certbot_certs:
