server {
    listen 80;
    server_name propcount.ru www.propcount.ru 77.91.100.153 _;

    root /usr/share/nginx/html;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location = /panel {
        return 301 /panel/;
    }

    location /panel/ {
        try_files $uri $uri/ /panel/index.html;
    }
}
