"""init

Revision ID: df63e52465f4
Revises: 
Create Date: 2026-08-28 00:12:01.155925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision = 'df63e52465f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linked_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linked_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_files_linked', ['linked_type', 'linked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_storage_key'), ['storage_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_files_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objects_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_plan'), ['plan'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('tenant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_profiles_inn'), ['inn'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'inn', name='uq_tenants_user_inn')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index('ix_tenants_inn', ['inn'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.create_table('cadastre_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cadastral_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'number', name='uq_cadastre_entries_object_number')
    )
    with op.batch_alter_table('cadastre_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastre_entries_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastre_entries_object_id'), ['object_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('utility_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pay_by', sa.Date(), nullable=False),
    sa.Column('amounts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utility_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utility_bills_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_bills_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_bills_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_bills_user_id'), ['user_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rent_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cadastre_id', sa.Integer(), nullable=True),
    sa.Column('utility_payers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cadastre_id'], ['cadastre_entries.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_cadastre_id'), ['cadastre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_object_id'), ['object_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_bill_id', sa.Integer(), nullable=True),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_bill_id'], ['utility_bills.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_source_bill_id'), ['source_bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_user_id'), ['user_id'], unique=False)

    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('rent_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leases_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leases_user_id'))
        batch_op.drop_index(batch_op.f('ix_leases_unit_id'))
        batch_op.drop_index(batch_op.f('ix_leases_tenant_id'))

    op.drop_table('leases')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_user_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_unit_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_source_bill_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_period'))
        batch_op.drop_index(batch_op.f('ix_invoices_kind'))
        batch_op.drop_index(batch_op.f('ix_invoices_due_date'))

    op.drop_table('invoices')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_object_id'))
        batch_op.drop_index(batch_op.f('ix_units_number'))
        batch_op.drop_index(batch_op.f('ix_units_cadastre_id'))

    op.drop_table('units')
    with op.batch_alter_table('utility_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utility_bills_user_id'))
        batch_op.drop_index(batch_op.f('ix_utility_bills_period'))
        batch_op.drop_index(batch_op.f('ix_utility_bills_object_id'))
        batch_op.drop_index(batch_op.f('ix_utility_bills_file_id'))

    op.drop_table('utility_bills')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_object_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))

    op.drop_table('transactions')
    with op.batch_alter_table('cadastre_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastre_entries_object_id'))
        batch_op.drop_index(batch_op.f('ix_cadastre_entries_number'))

    op.drop_table('cadastre_entries')
    op.drop_table('user_roles')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_name'))
        batch_op.drop_index('ix_tenants_inn')

    op.drop_table('tenants')
    with op.batch_alter_table('tenant_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_profiles_inn'))

    op.drop_table('tenant_profiles')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objects_user_id'))
        batch_op.drop_index(batch_op.f('ix_objects_type'))
        batch_op.drop_index(batch_op.f('ix_objects_address'))

    op.drop_table('objects')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_files_storage_key'))
        batch_op.drop_index('ix_files_linked')
        batch_op.drop_index(batch_op.f('ix_files_kind'))

    op.drop_table('files')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
